lab02/cilindro/urls.py
from django.urls import path

from . import views

app_name = 'cilindro'

urlpatterns = [
    path('', views.index, name='index'),
    path('volumen', views.volumen, name='volumen')
]

lab02/encuesta/urls.py
from django.urls import path
from . import views

app_name = 'encuesta'
urlpatterns = [
    path('',views.index,name='index'),
    path('enviar',views.enviar,name='enviar'),
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('operaciones/', include('operaciones.urls')),
    path('cilindro/', include('cilindro.urls')),
    path('admin/', admin.site.urls),
]

lab02/operaciones/urls.py
from django.urls import path

from . import views

app_name = 'operaciones'

urlpatterns = [
    path('', views.index, name='index'),
    path('enviar', views.enviar, name='enviar'),
]

lab02/cilindro/views.py
from django.shortcuts import render
import math

# Create your views here.
def index(request):
    context = {
        'titulo' : "Volumen de un cilindro",
    }
    return render(request, 'cilindro/formulario.html', context)

def volumen(request):
    h = int(request.POST['h'])
    r = int(request.POST['r'])
    unidad = request.POST['unidad']

    vol = math.pi * r**2 * h

    titulo = "Volumen de un cilindro en " + unidad

    context = {
        'titulo' : titulo,
        'h' : h,
        'r' : r,
        'v' : vol,
        'unidad' : unidad,
    }
    return render(request, 'cilindro/respuesta.html', context)

lab02/encuesta/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context = {
        'titulo' : 'Formulario',
    }
    return render(request, 'encuesta/formulario.html', context)

def enviar(request):
    context = {
        'titulo' : 'Respuesta',
        'nombre' : request.POST['nombre'],
        'clave' : request.POST['password'],
        'educacion' : request.POST['educacion'],
        'nacionalidad' : request.POST['nacionalidad'],
        'idiomas' : request.POST.getlist('idiomas'),
        'correo' : request.POST['email'],
        'website' : request.POST['sitioweb'],
    }
    return render(request, 'encuesta/respuesta.html', context)

lab02/operaciones/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context = {
        'titulo' : "Operaciones Aritmeticas :D",
    }
    return render(request, 'operaciones/formulario.html', context)

def enviar(request):

    op = request.POST.get('operation')
    num1 = int(request.POST.get('num1')) 
    num2 = int(request.POST.get('num2'))
    result = 0

    if op == "addition":
        result = num1 + num2
        op = "Suma"
    if op == "substraction":
        result = num1 - num2
        op = "Menos"
    if op == "multiplication":
        result = num1 * num2
        op = "Multiplicacion"
    if op == "division":
        result = num1 / num2
        op = "Division"

    context = {
        'titulo' : "Operaciones Aritmeticas :D",
        'num1' : num1,
        'num2' : num2,
        'op' : op,
        'result': result,
    }
    return render(request, 'operaciones/respuesta.html', context)

lab02/cilindro/templates/cilindro/formulario.html
<h2>{{titulo}}</h2>

<form action="{% url 'cilindro:volumen' %}" method="post">
	{% csrf_token %} Altura:
	<input type="text" name="h" /><br />
	Radio:
	<input type="text" name="r" /><br />
	Unidades:
	<select name="unidad">
		<option value="m">Metros</option>
		<option value="cm">Centimetros</option>
		<option value="pies">Pies</option>
		<option value="pulgadas">Pulgadas</option>
	</select>
	<input type="submit" name="volumen" value="Enviar" /><br />
</form>

lab02/cilindro/templates/cilindro/respuesta.html
<h2>{{titulo}}</h2>
<div>
	<p>Altura: {{h}} {{unidad}}</p>
	<p>Radio: {{r}}</p>
	<p>Volumen: {{v}} {{unidad}} cubicos</p>
</div>

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{titulo}}</h2>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>
    Contraseña:
    <input type="password" name="password"><br>
    Educacion:
    <select name="educacion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="educacion-obligatoria" selected="selected">Educacion Obligatoria</option>
        <option value="formacion-profesional">Formacion profesional</option>
        <option value="universidad">Universidad</option>
    </select> <br>
    Nacionalidad:
    <input type="radio" name="nacionalidad" value="hispana">Hispana</input>
    <input type="radio" name="nacionalidad" value="otrar">Otra</input><br>
    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
    <input type="checkbox" name="idiomas" value="ingles">Ingles</input>
    <input type="checkbox" name="idiomas" value="francés">Francés</input>
    <input type="checkbox" name="idiomas" value="aleman">Aleman</input><br>
    Email:
    <input type="text" name="email"><br>
    Sitio Web:
    <input type="text" name="sitioweb"><br>
    //boton de enviar
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{titulo}}</h2>
<p>Nombre : {{ nombre }}</p>
<p>Clave : {{ clave }}</p>
<p>Educación : {{ educacion }}</p>
<p>Nacionalidad : {{ nacionalidad }}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
        <li>{{ item }}</li>
    {% endfor %}
</ul>
<p>Email : {{ correo }}</p>
<p>Sitio web: {{ website }}</p>

lab02/operaciones/templates/operaciones/formulario.html
<h2>{{titulo}}</h2>
<form action="{% url 'operaciones:enviar' %}" method="post">
	{% csrf_token %} Number 1:
	<input type="text" name="num1" maxlength="15" /><br />
	Number 2:
	<input type="text" name="num2" maxlength="15" /><br />
	Operacion:
	<select name="operation">
		<option value="addition">Addition</option>
		<option value="substraction">Substraction</option>
		<option value="multiplication">Multiplication</option>
		<option value="division">Division</option>
	</select>

	<input type="submit" name="submit" value="Enviar" />
</form>

lab02/operaciones/templates/operaciones/respuesta.html
<h2>{{titulo}}</h2>
<div>
	<p>Numero 1: {{num1}}</p>
	<p>Numero 2: {{num2}}</p>
	<p>Operacion: {{op}}</p>
	<p>Resultado: {{result}}</p>
</div>